version: "3.9"
services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: testing
      POSTGRES_USER: elumian
      POSTGRES_PASSWORD: Columbian12
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
