import { schemaTables, options, retrunVarchar, schemaCreate } from './types'
import { DB as db } from '@DB/index'

class Schema {
  private DB: any
  constructor() {
    this.DB = new db()
  }
  public create(schema_name: string, tables: schemaTables): schemaCreate {
    let tablesName: Array<string> = Object.keys(tables) as string[]
    let valuesColumns: Array<string> = tablesName.map((key) => {
      return `CREATE TABLE IF NOT EXISTS "${schema_name}"."${key}" (
      ${Object.keys(tables[key] as { [key: string]: Array<string> })
        .map((columns) => {
          let column: Array<string> = tables[key]![columns] as Array<string>
          return `"${columns}" ${column.toString().replace(/,/g, ' ')}\\`
        })
        .toString()
        .replace(/,/g, '\n')}
      "created_at" timestamp default 'now()'\\
      "updated_at" timestamp default 'now()'
      );`
    })
    let query = {
      schema: `CREATE SCHEMA IF NOT EXISTS "${schema_name}";`,
      tables: `${valuesColumns
        .toString()
        .replace(/,/g, '')
        .replace(/(\\)|(,\s)/g, ',')}`.replace(/(\s{2,})/g, ''),
      ref: ``,
    }
    return query
  }
  public drop(schema_name: string, tables: Array<string>) {
    this.DB.queryExec(
      tables
        .map((tableName) => {
          return `DROP TABLE IF EXISTS "${schema_name}"."${tableName}" CASCADE;`
        })
        .toString()
        .replace(/,/g, '')
        .replace(/(;\s{1,})/g, 'x')
    )
  }
}

const options: options = {
  varchar: (length: number = 255): retrunVarchar => {
    return `varchar(${length})`
  },
  smallInt: 'SMALLINT',
  bigInt: 'BIGINT',
  text: 'TEXT',
  pk: 'PRIMARY KEY',
  increment: 'GENERATED BY DEFAULT AS IDENTITY',
  unique: 'UNIQUE',
  notNull: 'NOT NULL',
  boolean: 'BOOLEAN',
  bool: 'BOOL',
  timeStamp: 'TIMESTAMP',
}

export { Schema, options }
